[project]
name = "oracle-doc"
version = "0.1.0"
description = "Oracle Database Documentation MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "html2text>=2025.4.15",
    "mcp>=1.12.3",
    "whoosh>=2.7.4",
]
