name: Matrix Build
on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    needs: get-directories
    strategy:
      matrix:
        directory: ${{ fromJson(needs.get-directories.outputs.directories) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv and setup Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.19"

      - name: Sync
        working-directory: src/${{ matrix.directory }}
        run: uv sync --locked --all-extras --dev
        
      - name: Test
        working-directory: src/${{ matrix.directory }}
        run: uv run pytest

      - name: Build
        working-directory: src/${{ matrix.directory }}
        run: uv build

      - name: Test install
        working-directory: src/${{ matrix.directory }}
        run: uv pip install .
          

  get-directories:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.get-directories.outputs.directories }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get directories
        id: get-directories
        run: |
          directories=$(ls src | jq -R -s -c 'split("\n")[:-1]')
          echo "directories=$directories" >> $GITHUB_OUTPUT
